### ISSUE TITLE
data 0

### ISSUE THREAD

**Issue by frenchkiss38** [klatremis/esphome-for-deye#1]
[hello,]
I followed your tutorial but I have feedback at 0 in home assistant. I do not understand ...

I have model SUN-6K-SG03LP1-EU
In the menu I am in MASTER modbus sn:01
Attached yaml file + logs
# #
![IMG20230120214752](https://user-images.githubusercontent.com/116593021/214132047-7445854c-3dd9-43ee-a6ec-f3d25b3ef127.jpg)
![IMG20230120214738](https://user-images.githubusercontent.com/116593021/214132135-846759e4-6821-4b51-8b88-db62409eafeb.jpg)

[deye 6k.txt](https://github.com/klatremis/esphome-for-deye/files/10483054/deye.6k.txt)

[logs_deye-6k_logs (1).txt](https://github.com/klatremis/esphome-for-deye/files/10483105/logs_deye-6k_logs.1.txt)

**Comment by kababoom** [comment]
SUN-SG03LP1 is a single phase inverter, the addresses are different from the LP3 but if you convert them it should work.

**Comment by pvprodk** [comment]
Also, it looks like you have only connected GND, RXD and TXD on the TTL to RS485 print? It needs 3.3v VCC as well.

**Comment by klatremis** [comment]
As wrote, i cant support this as i don't have the inverter.
