### ISSUE TITLE
what is the use of Grid_Charge?

### ISSUE THREAD

**Issue by Duckshousemacservice** [klatremis/esphome-for-deye#10]
adress 130

maybe a stupid Q?

what does it do?

mvh andy
og tak for kode!

**Comment by kababoom** [comment]
It enables charging from grid, see page 30

https://www.deyeinverter.com/deyeinverter/2022/04/12/manual-sun-(5-12)k-sg04lp3-au-deye-1.pdf

**Comment by Duckshousemacservice** [comment]
thanks
