### ISSUE TITLE
Question: Chances this could work for the SUN-5K-SG03LP1?

### ISSUE THREAD

**Issue by kiss81** [klatremis/esphome-for-deye#13]
Any chance this same hardware / software (with some modifications) could work on the SUN-5K-SG03LP1?
If I can control the AC -> DC charge and DC -> AC discharge I am happy. :)
Otherwise I might buy one the SG04LP3 inverters to be sure..

**Comment by klatremis** [comment]
I dont know, and i can only support the three phase inverters unfurtenly. 

1 phase inverters is not allowed in Denmark in more than 3,6kW models (16A). So a 5k will never be approved to use here.
