### ISSUE TITLE
RS485/TTL-board brænder ofte af. 

### ISSUE THREAD

**Issue by zaprodk** [klatremis/esphome-for-deye#17]
Hej. Der er rigtig mange folk der oplever af RS485/TTL board brænder af da der står en spænding hen over modulet (lækstrøm) og så futter chippen af. Kan du ikke skrive i vejledningen at man bør "luse" GND tværs over modulet fra side til side? Det løser problemet.

**Comment by MyHekla** [comment]
anvender du separat strømforsyning til ESP og anvender du samme til modulet og hvilket modul anvender du?

**Comment by zaprodk** [comment]
> anvender du separat strømforsyning til ESP og anvender du samme til modulet og hvilket modul anvender du?

Jeg har ikke selv setup'et, men formoder at folk følger guiden her på siden. X/Y-kondensatorer i netfiltet på de to enheder kan skabe lækstrøm der brænder chippen af.
Jeg er bare elektroniknørd der hjælper med at finde ud af hvorfor tingene går galt en gang imellem :)

**Comment by MyHekla** [comment]
Hvis der anvendes det setup der er beskrevet her er de 2 GND allerede forbundet - gennem inverteren. Den GND der er på rs485 siden er 'kun' en over/under beskyttelses GND - se link
https://electronics.stackexchange.com/questions/244425/how-is-this-rs485-module-working
 så det har intet på sig. Det er nok mere, som det også er beskrevet i en anden rapport' at spændingsforsyningen ikke er god nok. Jeg har selv samme problem og har pt en datalogger på. Jeg påtænker en løsning hvor jeg tager strøm fra min batteripakke.

**Comment by zaprodk** [comment]
Fair nok. Jeg tror at folk forsyner ESP'en med en USB-strømforsyning eller noget andet HA-relareret hardware, og det er her balladen opstår. Hvis man tager strømforsyningen fra inverteren selv er der selvfølgelig fælles GND, men i tilfælde hvor folk ikke gør det, der sker sære ting.

**Comment by MyHekla** [comment]
Det er stadig ikke det der er problemet/løsningen. GND er ikke nødvendig med et balanceret signal. GND er kun til beskyttelse af  ind/udgang på 485 siden.

**Comment by Breinholm-coder** [comment]
@MyHekla 
Det er altså ikke korrekt: Uden GND vil de to A og B signaler flyde uden reference - Det er en misforståelse at RS485 ikke behøver GND. Parsnoning og differenssignaler hæver støj-imuniteten.

**Comment by zaprodk** [comment]
@Breinholm-coder exactly ...
Det er det samme som CAN-bus i biler. GND er nædvendigt, ellers kunne der være en høj spænding imellem enhederne der brænder line-drivers af. Og det er helt sikkert det der sker med disse boards. Udstyret i hver ende er tøjret med forskellig reference og pludselig står der 127-ish volt imellem to steder, og så står line-driveren af.

**Comment by Breinholm-coder** [comment]
Hej MyHekla,

Tror vi er næsten enige - undtagen hvad GND gør for signalkvaliteten: Er
der ingen common-mode spændingsforskel imellem de kommunikerende parter vil
en GND forbindelse ikke ændre noget. Men er der for eksempel over 7 V
common-mode støj imellem parterne vil en GND forbindelse være guld værd til
at nedsætte common-mode forskellen. TIA RS-485 standarden foreskriver
faktisk en fælles reference forbindelse.

MVH / Peter Breinholm

Den tirs. 5. sep. 2023 kl. 09.09 skrev MyHekla ***@***.***>:
