### ISSUE TITLE
Home Assistant Energy Dashboard Error

### ISSUE THREAD

**Issue by linuxdep** [klatremis/esphome-for-deye#7]
Hi, nice project, many thanks.

I wanted to insert the total PV production in the Energy Dashboard, but this fails because there seems to be no parameter "last_reset" for it. How can I adjust this so that the data arrives in the dashboard?

![grafik](https://user-images.githubusercontent.com/39172860/224824597-f182c7bc-f6bb-4b3a-8c7b-78863c6f45a2.png)

**Comment by gmidohan** [comment]
Maybe this is helpful: different device same problem 
[https://community.home-assistant.io/t/energy-dashboard-last-reset-missing/406733](https://community.home-assistant.io/t/energy-dashboard-last-reset-missing/406733)

**Comment by gplex83** [comment]
change state_class: "measurement"
to   state_class: "total_increasing"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "sun12k-Total PV Production"  #Cumulative Production 
    id: sun12k_Total_PV_Production
    register_type: holding
    address: 534
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_DWORD_R
    skip_updates: ${skip_updates}
    filters:
      - multiply: 0.1

**Comment by linuxdep** [comment]
thanks
